version: "3.4"
services:
  subversion:
    build:
      context: ./subversion
      dockerfile: ./Dockerfile
      network: host
    container_name: subversion
    user: root
    ports:
      - "80:80"
    privileged: true
    volumes:
      - ./data/svn:/var/lib/svn
      - ./subversion/conf/dav_svn.passwd:/etc/apache2/dav_svn.passwd
#    environment:

    restart: always
